import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'

import '../styles/globals.css'

import { Footer } from '@/components/Footer'
import { Navigation } from '@/components/Navgation'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={rubik.className}>
                <div className="bg-gray-900">
                    <Navigation />

                    <main className="min-h-[calc(100vh-48px)] mt-[88px]">
                        {children}
                    </main>

                    <Footer />
                </div>
            </body>
        </html>
    )
}
